// Autogenerated from Pigeon (v22.4.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTGDGMessage;

@interface FLTGDGMessage : NSObject
+ (instancetype)makeWithPlatform:(nullable NSString *)platform
    date:(nullable NSString *)date
    passedParameter:(nullable NSNumber *)passedParameter
    isGDGAwesome:(nullable NSNumber *)isGDGAwesome;
@property(nonatomic, copy, nullable) NSString * platform;
@property(nonatomic, copy, nullable) NSString * date;
@property(nonatomic, strong, nullable) NSNumber * passedParameter;
@property(nonatomic, strong, nullable) NSNumber * isGDGAwesome;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FLTGetMessagesCodec(void);

@protocol FLTCalculatorApi
/// @return `nil` only when `error != nil`.
- (nullable FLTGDGMessage *)getCalculationPassedParameter:(NSInteger)passedParameter error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isWorkingWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLTCalculatorApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTCalculatorApi> *_Nullable api);

extern void SetUpFLTCalculatorApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTCalculatorApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
